-- Phase 1H sales / POS outward.
--
-- The store's first OUTWARD commercial transaction: goods handed over at the counter, GST charged,
-- an invoice number the store itself issues, stock leaving the ledger, and tender recorded.
--
-- Scope is deliberately one transaction shape: an over-the-counter / store-delivery sale, where the
-- goods are handed to the customer at the store. Delivery, shipping, inter-State dispatch and
-- bill-to/ship-to are NOT modelled here and must not be forced through this document — their
-- place-of-supply rules differ, and pretending otherwise would mis-tax real invoices.
--
-- Excluded on purpose: sales return, credit note, void-after-post, discount, scheme, credit sale,
-- receivable, accounting journal, cash/bank ledger, stock valuation, GST return filing.

-- Extend the append-only audit stream without editing the earlier migrations.
ALTER TABLE master_change_events RENAME TO master_change_events_phase1h0;

CREATE TABLE master_change_events (
    event_id TEXT PRIMARY KEY NOT NULL CHECK (
        length(event_id) = 36 AND substr(event_id, 15, 1) = '7'
        AND lower(substr(event_id, 20, 1)) IN ('8', '9', 'a', 'b')
    ),
    entity_type TEXT NOT NULL CHECK (entity_type IN (
        'unit_of_measure', 'dosage_form', 'pharmaceutical_company', 'company_identifier',
        'brand', 'hsn_code', 'tax_category', 'tax_rate_version', 'regulatory_category',
        'product', 'product_company_role', 'product_pack', 'store_pack_policy', 'barcode',
        'ingredient', 'salt_form', 'strength_unit', 'product_composition_component',
        'product_batch',
        'state_code', 'party', 'party_role', 'party_address',
        'store_tax_identity',
        'purchase_document',
        'controlled_formulation', 'price_control_version', 'product_price_control',
        'sale_document'
    )),
    entity_id TEXT NOT NULL CHECK (
        length(entity_id) = 36 AND substr(entity_id, 15, 1) = '7'
        AND lower(substr(entity_id, 20, 1)) IN ('8', '9', 'a', 'b')
    ),
    entity_revision INTEGER NOT NULL CHECK (entity_revision >= 1),
    action TEXT NOT NULL CHECK (action IN ('created', 'updated', 'archived', 'restored', 'posted')),
    occurred_at_utc TEXT NOT NULL CHECK (occurred_at_utc GLOB '????-??-??T??:??:??*Z'),
    reason TEXT,
    payload_schema_version INTEGER NOT NULL CHECK (payload_schema_version >= 1),
    change_payload TEXT NOT NULL CHECK (json_valid(change_payload)),
    actor_id TEXT,
    terminal_id TEXT
) STRICT;

INSERT INTO master_change_events
SELECT * FROM master_change_events_phase1h0;
DROP TABLE master_change_events_phase1h0;

CREATE INDEX master_change_events_entity_idx
ON master_change_events(entity_type, entity_id, entity_revision);

CREATE TRIGGER master_change_events_no_update
BEFORE UPDATE ON master_change_events
BEGIN
    SELECT RAISE(ABORT, 'master_change_events_are_append_only');
END;

CREATE TRIGGER master_change_events_no_delete
BEFORE DELETE ON master_change_events
BEGIN
    SELECT RAISE(ABORT, 'master_change_events_are_append_only');
END;

-- ---------------------------------------------------------------------------------------------
-- Document numbering.
--
-- A supplier invoice number is data the supplier gave us; a sale invoice number is OURS to issue,
-- and issuing it wrongly is a compliance failure. The counter lives in a row per
-- (store, series, financial year) and is incremented INSIDE the posting transaction, under the write
-- lock the posting already holds. Never MAX(number)+1, and never generated by a browser.
--
-- Because allocation is inside that transaction, a refused posting rolls the counter back with
-- everything else: a failed posting consumes no number, so the series has no gaps.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE document_number_series (
    id TEXT PRIMARY KEY NOT NULL CHECK (
        length(id) = 36 AND substr(id, 15, 1) = '7'
        AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')
    ),
    store_id TEXT NOT NULL REFERENCES store_identity(store_id) ON DELETE RESTRICT,
    document_kind TEXT NOT NULL CHECK (document_kind IN ('sale')),
    series_code TEXT NOT NULL CHECK (
        series_code = upper(trim(series_code)) AND length(series_code) BETWEEN 1 AND 16
        AND series_code NOT GLOB '*[^A-Z0-9]*'
    ),
    -- The Indian financial year the sequence belongs to, e.g. '2026-27'. Stored as a literal so it
    -- can never be recomputed differently later.
    financial_year TEXT NOT NULL CHECK (
        length(financial_year) = 7 AND substr(financial_year, 5, 1) = '-'
        AND financial_year NOT GLOB '*[^0-9-]*'
    ),
    next_value INTEGER NOT NULL CHECK (next_value >= 1),
    created_at_utc TEXT NOT NULL CHECK (created_at_utc GLOB '????-??-??T??:??:??*Z'),
    updated_at_utc TEXT NOT NULL CHECK (updated_at_utc GLOB '????-??-??T??:??:??*Z'),
    UNIQUE (store_id, document_kind, series_code, financial_year)
) STRICT;

-- ---------------------------------------------------------------------------------------------
-- Sale documents.
--
-- A Draft is mutable and has no invoice number, no snapshot and no stock effect. Posting is a named
-- command that freezes everything at once.
--
-- customer_party_id is NULLABLE and NULL means WALK-IN. There is deliberately no shared "Cash
-- Customer" party row: inventing one would pollute the party master with a row per counter and make
-- "how many customers do we have" meaningless.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE sale_documents (
    id TEXT PRIMARY KEY NOT NULL CHECK (
        length(id) = 36 AND substr(id, 15, 1) = '7'
        AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')
    ),
    store_id TEXT NOT NULL REFERENCES store_identity(store_id) ON DELETE RESTRICT,
    customer_party_id TEXT REFERENCES parties(id) ON DELETE RESTRICT,
    -- Invoice text for a walk-in who wants a name on the bill. Never identity, never a master row.
    customer_name_text TEXT CHECK (
        customer_name_text IS NULL OR length(trim(customer_name_text)) BETWEEN 1 AND 200
    ),
    business_date TEXT NOT NULL CHECK (business_date GLOB '????-??-??'),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'posted')),
    revision INTEGER NOT NULL DEFAULT 1 CHECK (revision >= 1),

    -- Allocated at posting, never before.
    series_code TEXT,
    financial_year TEXT,
    sequence_value INTEGER CHECK (sequence_value IS NULL OR sequence_value >= 1),
    document_number TEXT,

    -- Store snapshot, written at posting.
    store_gst_registration_status TEXT,
    store_normalized_gstin TEXT,
    store_place_of_supply_state_id TEXT,
    store_state_code TEXT,

    -- Customer snapshot, written at posting when one is identified.
    customer_display_name TEXT,
    customer_gst_registration_status TEXT,
    customer_normalized_gstin TEXT,
    customer_state_code TEXT,

    tax_treatment TEXT CHECK (
        tax_treatment IS NULL OR tax_treatment IN ('intra_state', 'inter_state')
    ),
    taxable_value_paise INTEGER NOT NULL DEFAULT 0 CHECK (taxable_value_paise >= 0),
    cgst_paise INTEGER NOT NULL DEFAULT 0 CHECK (cgst_paise >= 0),
    sgst_paise INTEGER NOT NULL DEFAULT 0 CHECK (sgst_paise >= 0),
    igst_paise INTEGER NOT NULL DEFAULT 0 CHECK (igst_paise >= 0),
    cess_paise INTEGER NOT NULL DEFAULT 0 CHECK (cess_paise >= 0),
    grand_total_paise INTEGER NOT NULL DEFAULT 0 CHECK (grand_total_paise >= 0),

    created_by_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    created_at_utc TEXT NOT NULL CHECK (created_at_utc GLOB '????-??-??T??:??:??*Z'),
    updated_at_utc TEXT NOT NULL CHECK (updated_at_utc GLOB '????-??-??T??:??:??*Z'),
    posted_by_user_id TEXT REFERENCES users(id) ON DELETE RESTRICT,
    posted_at_utc TEXT CHECK (posted_at_utc IS NULL OR posted_at_utc GLOB '????-??-??T??:??:??*Z'),

    posting_idempotency_key TEXT CHECK (
        posting_idempotency_key IS NULL OR (
            length(posting_idempotency_key) = 36 AND substr(posting_idempotency_key, 15, 1) = '7'
            AND lower(substr(posting_idempotency_key, 20, 1)) IN ('8', '9', 'a', 'b')
        )
    ),
    posting_fingerprint TEXT CHECK (
        posting_fingerprint IS NULL OR length(posting_fingerprint) = 64
    ),

    -- A draft has nothing posted about it; a posted sale has all of it.
    CHECK (
        (status = 'draft' AND document_number IS NULL AND sequence_value IS NULL
            AND posted_at_utc IS NULL AND posted_by_user_id IS NULL
            AND tax_treatment IS NULL AND posting_idempotency_key IS NULL)
        OR (status = 'posted' AND document_number IS NOT NULL AND sequence_value IS NOT NULL
            AND series_code IS NOT NULL AND financial_year IS NOT NULL
            AND posted_at_utc IS NOT NULL AND posted_by_user_id IS NOT NULL
            AND tax_treatment IS NOT NULL AND posting_idempotency_key IS NOT NULL)
    )
) STRICT;

-- The number the store issued is unique, and so is its place in the series. The database is the
-- authority for both, not the service.
CREATE UNIQUE INDEX sale_documents_number_uq
ON sale_documents(store_id, document_number)
WHERE document_number IS NOT NULL;

CREATE UNIQUE INDEX sale_documents_sequence_uq
ON sale_documents(store_id, series_code, financial_year, sequence_value)
WHERE sequence_value IS NOT NULL;

CREATE UNIQUE INDEX sale_documents_idempotency_uq
ON sale_documents(posting_idempotency_key)
WHERE posting_idempotency_key IS NOT NULL;

CREATE INDEX sale_documents_listing_idx
ON sale_documents(store_id, status, business_date);

CREATE INDEX sale_documents_customer_idx
ON sale_documents(customer_party_id)
WHERE customer_party_id IS NOT NULL;

-- ---------------------------------------------------------------------------------------------
-- Sale lines.
--
-- Every line states its own quantity basis, because "3" means nothing without it. There is no
-- decimal pack quantity anywhere: selling three tablets from a strip of ten is
-- (basis = base_unit, quantity_atoms = 3), permitted only where the frozen Pack policy allows it.
--
-- The rate is expressed in the SAME basis as the quantity, so the taxable value is always an exact
-- integer product and no division ever enters the money path.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE sale_lines (
    id TEXT PRIMARY KEY NOT NULL CHECK (
        length(id) = 36 AND substr(id, 15, 1) = '7'
        AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')
    ),
    sale_document_id TEXT NOT NULL REFERENCES sale_documents(id) ON DELETE RESTRICT,
    line_number INTEGER NOT NULL CHECK (line_number >= 1),
    product_id TEXT NOT NULL,
    product_pack_id TEXT NOT NULL,
    -- A sale always leaves a specific lot: there is no anonymous outward movement.
    batch_id TEXT NOT NULL,

    quantity_basis TEXT NOT NULL CHECK (quantity_basis IN ('pack', 'base_unit')),
    quantity_packs INTEGER CHECK (quantity_packs IS NULL OR quantity_packs >= 1),
    quantity_atoms INTEGER NOT NULL CHECK (quantity_atoms >= 1),
    selling_rate_paise INTEGER NOT NULL CHECK (
        selling_rate_paise >= 0 AND selling_rate_paise <= 100000000000
    ),

    -- Identity snapshots, so a posted invoice reprints exactly as issued years later.
    product_display_name TEXT,
    pack_display_label TEXT,
    base_unit_label TEXT,
    batch_number TEXT,
    batch_expires_on TEXT,
    batch_mrp_paise INTEGER CHECK (batch_mrp_paise IS NULL OR batch_mrp_paise > 0),

    -- Tax snapshots, written at posting.
    hsn_code_id TEXT,
    hsn_code TEXT,
    tax_category_id TEXT,
    tax_treatment_kind TEXT CHECK (
        tax_treatment_kind IS NULL
        OR tax_treatment_kind IN ('taxable', 'exempt', 'nil_rated', 'non_gst')
    ),
    tax_rate_version_id TEXT,
    cgst_basis_points INTEGER NOT NULL DEFAULT 0 CHECK (cgst_basis_points BETWEEN 0 AND 10000),
    sgst_basis_points INTEGER NOT NULL DEFAULT 0 CHECK (sgst_basis_points BETWEEN 0 AND 10000),
    igst_basis_points INTEGER NOT NULL DEFAULT 0 CHECK (igst_basis_points BETWEEN 0 AND 10000),
    cess_basis_points INTEGER NOT NULL DEFAULT 0 CHECK (cess_basis_points BETWEEN 0 AND 10000),

    -- Price-control snapshot (Phase 1H-0), so the posted line records what was assessed and what
    -- ceiling was in force — including an honest 'unknown', which is never read as "uncontrolled".
    price_control_status TEXT CHECK (
        price_control_status IS NULL
        OR price_control_status IN ('unknown', 'not_applicable', 'controlled')
    ),
    controlled_formulation_id TEXT,
    price_control_version_id TEXT,
    ceiling_price_paise INTEGER CHECK (ceiling_price_paise IS NULL OR ceiling_price_paise > 0),
    ceiling_basis TEXT CHECK (
        ceiling_basis IS NULL OR ceiling_basis IN ('per_base_unit', 'per_pack')
    ),

    taxable_value_paise INTEGER NOT NULL DEFAULT 0 CHECK (taxable_value_paise >= 0),
    cgst_paise INTEGER NOT NULL DEFAULT 0 CHECK (cgst_paise >= 0),
    sgst_paise INTEGER NOT NULL DEFAULT 0 CHECK (sgst_paise >= 0),
    igst_paise INTEGER NOT NULL DEFAULT 0 CHECK (igst_paise >= 0),
    cess_paise INTEGER NOT NULL DEFAULT 0 CHECK (cess_paise >= 0),
    line_total_paise INTEGER NOT NULL DEFAULT 0 CHECK (line_total_paise >= 0),

    created_at_utc TEXT NOT NULL CHECK (created_at_utc GLOB '????-??-??T??:??:??*Z'),
    updated_at_utc TEXT NOT NULL CHECK (updated_at_utc GLOB '????-??-??T??:??:??*Z'),

    -- The basis and the quantity it is expressed in must agree.
    CHECK (
        (quantity_basis = 'pack' AND quantity_packs IS NOT NULL)
        OR (quantity_basis = 'base_unit' AND quantity_packs IS NULL)
    ),
    UNIQUE (sale_document_id, line_number),
    FOREIGN KEY (product_pack_id, product_id) REFERENCES product_packs(id, product_id),
    FOREIGN KEY (batch_id, product_pack_id) REFERENCES product_batches(id, product_pack_id)
) STRICT;

CREATE INDEX sale_lines_document_idx ON sale_lines(sale_document_id, line_number);

-- ---------------------------------------------------------------------------------------------
-- Tender: operational evidence only.
--
-- No cash ledger, no bank ledger, no settlement, no receivable, no accounting posting. Phase 1H
-- validates exactly one tender row per sale; the table is a child from the start so split tender
-- later becomes a validation change rather than migration surgery.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE sale_tenders (
    id TEXT PRIMARY KEY NOT NULL CHECK (
        length(id) = 36 AND substr(id, 15, 1) = '7'
        AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')
    ),
    sale_document_id TEXT NOT NULL REFERENCES sale_documents(id) ON DELETE RESTRICT,
    method TEXT NOT NULL CHECK (method IN ('cash', 'card', 'upi')),
    amount_paise INTEGER NOT NULL CHECK (amount_paise > 0),
    reference_text TEXT CHECK (
        reference_text IS NULL OR length(trim(reference_text)) BETWEEN 1 AND 120
    ),
    created_at_utc TEXT NOT NULL CHECK (created_at_utc GLOB '????-??-??T??:??:??*Z')
) STRICT;

CREATE INDEX sale_tenders_document_idx ON sale_tenders(sale_document_id);

-- ---------------------------------------------------------------------------------------------
-- Posted immutability. A posted sale is a document that was issued to a customer: once the row is
-- posted it is frozen, and no posted row may be deleted. This mirrors the frozen purchase and
-- inventory append-only triggers.
-- ---------------------------------------------------------------------------------------------
CREATE TRIGGER sale_documents_posted_no_update
BEFORE UPDATE ON sale_documents
WHEN OLD.status = 'posted'
BEGIN
    SELECT RAISE(ABORT, 'sale_document_is_posted');
END;

CREATE TRIGGER sale_documents_posted_no_delete
BEFORE DELETE ON sale_documents
WHEN OLD.status = 'posted'
BEGIN
    SELECT RAISE(ABORT, 'sale_document_is_posted');
END;

CREATE TRIGGER sale_lines_posted_no_update
BEFORE UPDATE ON sale_lines
WHEN EXISTS (
    SELECT 1 FROM sale_documents
    WHERE id = OLD.sale_document_id AND status = 'posted'
)
BEGIN
    SELECT RAISE(ABORT, 'sale_document_is_posted');
END;

CREATE TRIGGER sale_lines_posted_no_delete
BEFORE DELETE ON sale_lines
WHEN EXISTS (
    SELECT 1 FROM sale_documents
    WHERE id = OLD.sale_document_id AND status = 'posted'
)
BEGIN
    SELECT RAISE(ABORT, 'sale_document_is_posted');
END;

-- Tender evidence is frozen with the document it belongs to.
CREATE TRIGGER sale_tenders_posted_no_update
BEFORE UPDATE ON sale_tenders
WHEN EXISTS (
    SELECT 1 FROM sale_documents
    WHERE id = OLD.sale_document_id AND status = 'posted'
)
BEGIN
    SELECT RAISE(ABORT, 'sale_document_is_posted');
END;

CREATE TRIGGER sale_tenders_posted_no_delete
BEFORE DELETE ON sale_tenders
WHEN EXISTS (
    SELECT 1 FROM sale_documents
    WHERE id = OLD.sale_document_id AND status = 'posted'
)
BEGIN
    SELECT RAISE(ABORT, 'sale_document_is_posted');
END;

-- A sale may only name a party that is an active customer of this store. Supplier eligibility is
-- untouched: enabling one role must never make the other optional.
CREATE TRIGGER sale_documents_customer_role_insert
BEFORE INSERT ON sale_documents
WHEN NEW.customer_party_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM party_roles
    WHERE party_id = NEW.customer_party_id AND role = 'customer' AND status = 'active'
)
BEGIN
    SELECT RAISE(ABORT, 'customer_not_eligible');
END;

CREATE TRIGGER sale_documents_customer_role_update
BEFORE UPDATE OF customer_party_id ON sale_documents
WHEN NEW.customer_party_id IS NOT NULL
 AND (OLD.customer_party_id IS NULL OR NEW.customer_party_id <> OLD.customer_party_id)
 AND NOT EXISTS (
    SELECT 1 FROM party_roles
    WHERE party_id = NEW.customer_party_id AND role = 'customer' AND status = 'active'
)
BEGIN
    SELECT RAISE(ABORT, 'customer_not_eligible');
END;

-- ---------------------------------------------------------------------------------------------
-- Inventory ledger: add the 'sale' movement type and a real provenance foreign key.
--
-- SQLite cannot alter a CHECK in place, so the table is rebuilt. EVERYTHING is preserved: every
-- column, constraint, foreign key, index and trigger from the Phase 1D ledger and the Phase 1G
-- purchase extension is reproduced verbatim below, and the frozen Phase 1D integrity tests are
-- re-run after a FORCED recompilation to prove the rebuild erased nothing.
-- ---------------------------------------------------------------------------------------------
ALTER TABLE inventory_movements RENAME TO inventory_movements_phase1g;

CREATE TABLE inventory_movements (
    id TEXT PRIMARY KEY NOT NULL CHECK (
        length(id) = 36 AND substr(id, 15, 1) = '7'
        AND lower(substr(id, 20, 1)) IN ('8', '9', 'a', 'b')
    ),
    store_id TEXT NOT NULL REFERENCES store_identity(store_id) ON DELETE RESTRICT,
    product_id TEXT NOT NULL,
    product_pack_id TEXT NOT NULL,
    batch_id TEXT,
    movement_type TEXT NOT NULL CHECK (
        movement_type IN ('opening_stock', 'adjustment', 'purchase', 'sale')
    ),
    quantity_delta_atoms INTEGER NOT NULL CHECK (
        quantity_delta_atoms <> 0
        AND quantity_delta_atoms BETWEEN -9000000000000000 AND 9000000000000000
    ),
    occurred_on TEXT NOT NULL CHECK (occurred_on GLOB '????-??-??'),
    reason TEXT CHECK (reason IS NULL OR length(trim(reason)) BETWEEN 1 AND 500),
    reverses_movement_id TEXT REFERENCES inventory_movements(id) ON DELETE RESTRICT,
    -- Durable provenance: which purchase line produced this inward.
    purchase_line_id TEXT REFERENCES purchase_lines(id) ON DELETE RESTRICT,
    -- Durable provenance: which sale line produced this outward.
    sale_line_id TEXT REFERENCES sale_lines(id) ON DELETE RESTRICT,
    idempotency_key TEXT NOT NULL CHECK (
        length(idempotency_key) = 36 AND substr(idempotency_key, 15, 1) = '7'
        AND lower(substr(idempotency_key, 20, 1)) IN ('8', '9', 'a', 'b')
    ),
    posted_by_user_id TEXT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    posted_at_utc TEXT NOT NULL CHECK (posted_at_utc GLOB '????-??-??T??:??:??*Z'),
    CHECK (movement_type <> 'opening_stock' OR quantity_delta_atoms > 0),
    CHECK (reverses_movement_id IS NULL OR movement_type = 'adjustment'),
    -- Provenance and type agree in both directions, so a purchase movement can never be anonymous
    -- and a non-purchase movement can never claim a purchase line.
    CHECK (movement_type <> 'purchase' OR purchase_line_id IS NOT NULL),
    CHECK (purchase_line_id IS NULL OR movement_type = 'purchase'),
    -- A purchase brings stock in.
    CHECK (movement_type <> 'purchase' OR quantity_delta_atoms > 0),
    -- The same pairing for a sale, which takes stock out.
    CHECK (movement_type <> 'sale' OR sale_line_id IS NOT NULL),
    CHECK (sale_line_id IS NULL OR movement_type = 'sale'),
    CHECK (movement_type <> 'sale' OR quantity_delta_atoms < 0),
    -- A sale always leaves a specific lot.
    CHECK (movement_type <> 'sale' OR batch_id IS NOT NULL),
    UNIQUE (idempotency_key),
    FOREIGN KEY (product_pack_id, product_id) REFERENCES product_packs(id, product_id),
    FOREIGN KEY (batch_id, product_pack_id) REFERENCES product_batches(id, product_pack_id)
) STRICT;

INSERT INTO inventory_movements (
    id, store_id, product_id, product_pack_id, batch_id, movement_type, quantity_delta_atoms,
    occurred_on, reason, reverses_movement_id, purchase_line_id, idempotency_key,
    posted_by_user_id, posted_at_utc
)
SELECT
    id, store_id, product_id, product_pack_id, batch_id, movement_type, quantity_delta_atoms,
    occurred_on, reason, reverses_movement_id, purchase_line_id, idempotency_key,
    posted_by_user_id, posted_at_utc
FROM inventory_movements_phase1g;

DROP TABLE inventory_movements_phase1g;

CREATE UNIQUE INDEX inventory_movements_reversal_uq
ON inventory_movements(reverses_movement_id)
WHERE reverses_movement_id IS NOT NULL;

CREATE INDEX inventory_movements_balance_idx
ON inventory_movements(store_id, product_pack_id, batch_id);

CREATE INDEX inventory_movements_history_idx
ON inventory_movements(store_id, occurred_on, posted_at_utc);

CREATE INDEX inventory_movements_product_idx
ON inventory_movements(store_id, product_id);

CREATE INDEX inventory_movements_purchase_idx
ON inventory_movements(purchase_line_id)
WHERE purchase_line_id IS NOT NULL;

CREATE INDEX inventory_movements_sale_idx
ON inventory_movements(sale_line_id)
WHERE sale_line_id IS NOT NULL;

CREATE TRIGGER inventory_movements_no_update
BEFORE UPDATE ON inventory_movements
BEGIN
    SELECT RAISE(ABORT, 'inventory_movements_are_append_only');
END;

CREATE TRIGGER inventory_movements_no_delete
BEFORE DELETE ON inventory_movements
BEGIN
    SELECT RAISE(ABORT, 'inventory_movements_are_append_only');
END;

CREATE TRIGGER inventory_movements_integrity_insert
BEFORE INSERT ON inventory_movements
WHEN NOT EXISTS (
        SELECT 1 FROM product_packs pack
        JOIN products product ON product.id = pack.product_id
        WHERE pack.id = NEW.product_pack_id
          AND pack.status = 'active'
          AND product.status = 'active'
    )
 OR (NEW.batch_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM product_batches WHERE id = NEW.batch_id AND status = 'active'
    ))
BEGIN
    SELECT RAISE(ABORT, 'inventory_movement_conflict');
END;
